spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

secret:
   key: ${SECRET_KEY:src/main/resources/secret/secret-key}