spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

server:
  servlet:
    context-path: /auth

logging:
  level:
    root: INFO
    br.com.fiap.postech.authserver: info
    br.com.fiap.postech.authserver.error: error

secret:
   key: ${SECRET_KEY:src/main/resources/secret/secret-key}
